//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDVentaCompraEntities : DbContext
    {
        public BDVentaCompraEntities()
            : base("name=BDVentaCompraEntities")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCompra> TCompra { get; set; }
        public virtual DbSet<TDetalleCompra> TDetalleCompra { get; set; }
        public virtual DbSet<TDetalleGasto> TDetalleGasto { get; set; }
        public virtual DbSet<TGasto> TGasto { get; set; }
        public virtual DbSet<TProducto> TProducto { get; set; }
        public virtual DbSet<TGananciaVenta> TGananciaVenta { get; set; }
    }
}
